import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🏠 Getting Started',
      collapsed: false,
      items: ['intro'],
    },
    {
      type: 'category',
      label: '📘 Week 1-2: Core Networking',
      collapsed: false,
      items: [
        'week1-2/README',
        'week1-2/D1_OSI_Model',
        'week1-2/D2_IP_Subnetting',
        'week1-2/D3_DNS',
        'week1-2/D4_TCP_UDP',
        'week1-2/D5_Routing_Switching_ARP',
        'week1-2/D6_NAT',
        'week1-2/D7_Week1_Scenario',
        'week1-2/D8_iptables',
        'week1-2/D9_Protocols',
        'week1-2/D10_VLANs',
        'week1-2/D11_chronyD',
        'week1-2/D12_systemd',
        'week1-2/D13_Cgroups',
        'week1-2/D14_Week2_Scenario',
      ],
    },
    {
      type: 'category',
      label: '🐧 Week 3-4: Linux & Containers',
      collapsed: true,
      items: [
        'week3-4/README',
        'week3-4/D15_Network_Namespaces',
        'week3-4/D16_veth_Pairs',
        'week3-4/D17_Linux_Bridge',
        'week3-4/D18_iptables_NAT',
        'week3-4/D19_conntrack',
        'week3-4/D20_Docker_Networking',
        'week3-4/D21_Week3_Scenario',
        'week3-4/D22_Linux_Bonding',
        'week3-4/D23_NMState',
        'week3-4/D24_tcpdump_Basics',
        'week3-4/D25_tcpdump_Advanced',
        'week3-4/D26_nsenter',
        'week3-4/D27_Container_Network_Trace',
        'week3-4/D28_Week4_Scenario',
      ],
    },
    {
      type: 'category',
      label: '☸️ Week 5-6: Kubernetes',
      collapsed: true,
      items: [
        'week5-6/README',
        'week5-6/D29_kind_Setup',
        'week5-6/D30_K8s_4_Rules',
        'week5-6/D31_ClusterIP_Service',
        'week5-6/D32_CoreDNS',
        'week5-6/D33_Endpoints',
        'week5-6/D34_NodePort_Ingress',
        'week5-6/D35_Week5_Scenario',
        'week5-6/D36_NetworkPolicy',
        'week5-6/D37_CNI_Deep_Dive',
        'week5-6/D38_DNS_Troubleshooting',
        'week5-6/D39_kube_proxy_IPVS',
        'week5-6/D40_Service_Troubleshooting',
        'week5-6/D41_Wireshark_Intro',
        'week5-6/D42_Week6_Scenario',
      ],
    },
    {
      type: 'category',
      label: '🔴 Week 7: OpenShift Deep Dive',
      collapsed: true,
      items: [
        'week7/README',
        'week7/D43_OVS_Fundamentals',
        'week7/D44_OVS_Flow_Tables',
        'week7/D45_OVN_Architecture',
        'week7/D46_OVN_Traffic_Flows',
        'week7/D47_Routes_HAProxy',
        'week7/D48_DNS_EgressIP',
        'week7/D49_Week7_Scenario',
      ],
    },
    {
      type: 'category',
      label: '📋 Cheat Sheets',
      collapsed: true,
      items: [
        'cheat-sheets/README',
        'cheat-sheets/Master_Commands_QuickRef',
        'cheat-sheets/Phase1_Core_Networking_CheatSheet',
        'cheat-sheets/Phase2_Linux_Container_CheatSheet',
        'cheat-sheets/Phase3_Kubernetes_CheatSheet',
        'cheat-sheets/Phase4_OpenShift_CheatSheet',
      ],
    },
  ],
};

export default sidebars;
